package api

import (
	"crypto/rand"
	"encoding/base64"
	"net/http"
	"strings"
)

func (s *Server) adminConsole(response http.ResponseWriter, _ *http.Request) {
	nonceBytes := make([]byte, 18)
	if _, err := rand.Read(nonceBytes); err != nil {
		s.internalError(response, err)
		return
	}
	nonce := base64.RawStdEncoding.EncodeToString(nonceBytes)
	response.Header().Set("Content-Type", "text/html; charset=utf-8")
	response.Header().Set("Cache-Control", "no-store")
	response.Header().Set("Referrer-Policy", "no-referrer")
	response.Header().Set("X-Content-Type-Options", "nosniff")
	response.Header().Set("Content-Security-Policy", "default-src 'self'; style-src 'nonce-"+nonce+"'; script-src 'nonce-"+nonce+"'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'; base-uri 'none'; form-action 'none'")
	_, _ = response.Write([]byte(strings.ReplaceAll(adminConsoleHTML, "{{NONCE}}", nonce)))
}

const adminConsoleHTML = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light dark"><title>책결 운영 센터</title>
<style nonce="{{NONCE}}">
:root{font-family:Inter,Pretendard,"Noto Sans KR",system-ui,sans-serif;color-scheme:light;--canvas:#f3f0e8;--surface:#fffdf8;--surface2:#ebe7dd;--ink:#19362d;--muted:#69766f;--line:#dcd7cb;--brand:#2f6754;--brand2:#214d3f;--accent:#c66d52;--ok:#31715a;--warn:#9a681f;--danger:#b34838;--shadow:0 18px 48px rgba(34,58,48,.09)}
:root[data-theme="dark"]{color-scheme:dark;--canvas:#101713;--surface:#18231e;--surface2:#222f29;--ink:#edf5f0;--muted:#aab8b0;--line:#33463c;--brand:#72ad91;--brand2:#95c8ad;--accent:#e08a70;--ok:#79b99a;--warn:#e0b46b;--danger:#ed8f80;--shadow:0 18px 48px rgba(0,0,0,.22)}
@media(prefers-color-scheme:dark){:root:not([data-theme="light"]){color-scheme:dark;--canvas:#101713;--surface:#18231e;--surface2:#222f29;--ink:#edf5f0;--muted:#aab8b0;--line:#33463c;--brand:#72ad91;--brand2:#95c8ad;--accent:#e08a70;--ok:#79b99a;--warn:#e0b46b;--danger:#ed8f80;--shadow:0 18px 48px rgba(0,0,0,.22)}}
*{box-sizing:border-box}body{margin:0;background:var(--canvas);color:var(--ink);min-height:100vh}.shell{max-width:1280px;margin:auto;padding:26px 22px 72px}.top{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:22px}.brand{display:flex;align-items:center;gap:13px}.mark{width:46px;height:46px;border-radius:15px;background:var(--brand);color:var(--surface);display:grid;place-items:center;font-weight:950;font-size:19px;box-shadow:0 10px 22px rgba(47,103,84,.22)}h1{font-size:25px;margin:0;letter-spacing:-.5px}.eyebrow{font-size:10px;font-weight:900;letter-spacing:1.8px;color:var(--brand);margin-bottom:3px}.top-actions{display:flex;align-items:center;gap:9px}.connection{display:flex;align-items:center;gap:7px;padding:8px 11px;border:1px solid var(--line);border-radius:999px;font-size:12px;color:var(--muted);background:var(--surface)}.dot{width:8px;height:8px;border-radius:50%;background:var(--muted)}.connection.online{color:var(--ok)}.connection.online .dot{background:var(--ok);box-shadow:0 0 0 4px color-mix(in srgb,var(--ok) 16%,transparent)}
button,input,select{font:inherit}button{cursor:pointer}.icon-button,.button,.tab{border:1px solid var(--line);background:var(--surface);color:var(--ink);border-radius:12px;font-weight:800}.icon-button{width:40px;height:40px}.button{padding:10px 14px}.button.primary{background:var(--brand);border-color:var(--brand);color:var(--surface)}.button.ghost{background:transparent}.button.danger{color:var(--danger);border-color:color-mix(in srgb,var(--danger) 38%,var(--line))}.button:disabled{opacity:.48;cursor:not-allowed}
.auth{display:grid;grid-template-columns:minmax(140px,.55fr) minmax(260px,1.4fr) auto auto;gap:10px;align-items:center;background:var(--surface);border:1px solid var(--line);border-radius:18px;padding:13px;box-shadow:var(--shadow);margin-bottom:16px}.field{width:100%;border:1px solid var(--line);background:var(--canvas);color:var(--ink);border-radius:11px;padding:11px 12px;outline:none}.field:focus{border-color:var(--brand);box-shadow:0 0 0 3px color-mix(in srgb,var(--brand) 16%,transparent)}
.notice{display:none;margin:0 0 14px;padding:11px 14px;border-radius:12px;background:color-mix(in srgb,var(--danger) 9%,var(--surface));color:var(--danger);font-size:13px;font-weight:700}.notice.show{display:block}.tabs{display:flex;gap:5px;padding:5px;background:var(--surface2);border-radius:15px;width:max-content;max-width:100%;margin-bottom:19px}.tab{border:0;background:transparent;padding:10px 15px;color:var(--muted)}.tab.active{background:var(--surface);color:var(--ink);box-shadow:0 5px 15px rgba(30,51,42,.09)}.tab .count{font-size:10px;background:var(--accent);color:white;border-radius:99px;padding:2px 6px;margin-left:5px}.view[hidden]{display:none!important}
.section-head{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:13px}.section-head h2{font-size:20px;margin:0}.section-head p{font-size:13px;color:var(--muted);margin:4px 0 0}.section-actions{display:flex;gap:8px;align-items:center}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.metric,.panel{background:var(--surface);border:1px solid var(--line);box-shadow:var(--shadow)}.metric{border-radius:17px;padding:17px}.metric-label{font-size:12px;color:var(--muted);font-weight:750}.metric strong{display:block;font-size:27px;margin:7px 0 2px;letter-spacing:-1px}.metric small{font-size:11px;color:var(--muted)}.metric.attention strong{color:var(--warn)}.metric.danger strong{color:var(--danger)}
.dashboard-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:13px}.panel{border-radius:18px;padding:18px}.panel-title{font-size:15px;margin:0 0 15px}.health-row{display:grid;grid-template-columns:1fr auto;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}.health-row:last-child{border-bottom:0}.health-label{font-size:13px}.health-meta{font-size:11px;color:var(--muted);margin-top:3px}.health-value{font-size:12px;font-weight:850;color:var(--ok)}.guide{padding:16px;border-radius:15px;background:var(--surface2);font-size:13px;line-height:1.62;margin-bottom:10px}.guide strong{display:block;margin-bottom:3px}.timestamp{font-size:11px;color:var(--muted)}
.log-tools{display:grid;grid-template-columns:150px minmax(180px,1fr) auto auto auto;gap:9px;margin-bottom:11px}.check{display:flex;align-items:center;gap:7px;white-space:nowrap;font-size:12px;color:var(--muted);padding:0 5px}.log-shell{background:#101714;color:#dce9e1;border-radius:18px;border:1px solid #314139;overflow:hidden;box-shadow:var(--shadow)}.log-head,.log-row{display:grid;grid-template-columns:112px 65px 60px minmax(180px,1fr);gap:10px;align-items:start}.log-head{padding:10px 14px;background:#19241f;color:#83988d;font-size:10px;font-weight:850;letter-spacing:.7px;text-transform:uppercase}.log-list{height:min(62vh,650px);min-height:390px;overflow:auto;overscroll-behavior:contain}.log-row{padding:10px 14px;border-top:1px solid #26332d;font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace}.log-row:hover{background:#16211c}.log-time{color:#80948a}.log-level{font-weight:900}.log-level.info{color:#86bfa3}.log-level.warn{color:#e4b768}.log-level.error{color:#f08e7d}.log-status{color:#9cac9f}.log-main{min-width:0;overflow-wrap:anywhere}.log-message{color:#e8f1ec}.log-context{color:#8fa198;margin-top:2px}.log-empty{height:100%;display:grid;place-items:center;text-align:center;color:#799086;padding:36px}.stream-state{display:inline-flex;align-items:center;gap:6px;font-size:11px;color:var(--muted)}.stream-state .dot{width:7px;height:7px}.stream-state.live{color:var(--ok)}.stream-state.live .dot{background:var(--ok);animation:pulse 1.8s infinite}@keyframes pulse{50%{opacity:.35}}
.moderation-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(290px,.75fr);gap:13px}.toolbar{display:flex;gap:8px;margin-bottom:12px}.list{display:grid;gap:10px}.report,.audit-item{background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:16px}.meta{display:flex;gap:6px;flex-wrap:wrap;font-size:11px;color:var(--muted)}.pill{background:var(--surface2);padding:5px 8px;border-radius:99px}.detail{white-space:pre-wrap;margin:13px 0;line-height:1.55;font-size:13px}.actions{display:flex;gap:7px;flex-wrap:wrap}.actions .button{padding:8px 10px;font-size:12px}.empty{padding:38px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:16px}.audit-item strong{display:block;font-size:13px;margin-bottom:5px}.audit-item .reason{font-size:12px;margin-bottom:6px}.audit-item .meta{line-height:1.5}
@media(max-width:900px){.cards{grid-template-columns:repeat(2,1fr)}.dashboard-grid,.moderation-grid{grid-template-columns:1fr}.log-tools{grid-template-columns:130px 1fr auto}.log-tools .check{grid-column:auto}.auth{grid-template-columns:1fr 1fr auto}.auth .disconnect{grid-column:3}}
@media(max-width:620px){.shell{padding:18px 13px 60px}.top{align-items:flex-start}.top-actions .connection{display:none}h1{font-size:21px}.mark{width:41px;height:41px}.auth{grid-template-columns:1fr}.auth .disconnect{grid-column:auto}.tabs{width:100%;overflow:auto}.tab{flex:1;white-space:nowrap;padding:9px 10px}.cards{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.metric{padding:14px}.metric strong{font-size:23px}.section-head{align-items:flex-start;flex-direction:column}.log-tools{grid-template-columns:1fr 1fr}.log-tools .search{grid-column:1/-1;grid-row:1}.log-head{display:none}.log-row{grid-template-columns:74px 52px 48px minmax(0,1fr);gap:6px;padding:9px 10px;font-size:10.5px}.log-list{height:58vh;min-height:360px}.panel{padding:14px}.toolbar{flex-wrap:wrap}}
</style></head><body><main class="shell">
<header class="top"><div class="brand"><div class="mark">책</div><div><div class="eyebrow">BOOKGYEOL OPERATIONS</div><h1>책결 운영 센터</h1></div></div><div class="top-actions"><div id="connection" class="connection"><span class="dot"></span><span>연결 안 됨</span></div><button class="icon-button" id="themeBtn" aria-label="테마 변경" title="테마 변경">◐</button></div></header>
<section class="auth" aria-label="운영자 연결"><input class="field" id="adminId" aria-label="운영자 식별자" placeholder="운영자 ID" value="owner" autocomplete="off"><input class="field" id="adminKey" type="password" aria-label="운영자 API 키" placeholder="ADMIN_API_KEY" autocomplete="off"><button class="button primary" id="connectBtn">연결</button><button class="button ghost disconnect" id="disconnectBtn">연결 해제</button></section>
<div id="notice" class="notice" role="status"></div>
<nav class="tabs" role="tablist" aria-label="관리자 기능"><button class="tab active" role="tab" aria-selected="true" data-view="dashboard">대시보드</button><button class="tab" role="tab" aria-selected="false" data-view="logs">실시간 로그</button><button class="tab" role="tab" aria-selected="false" data-view="moderation">신고 관리 <span id="reportBadge" class="count" hidden>0</span></button></nav>

<section id="dashboard" class="view" role="tabpanel">
 <div class="section-head"><div><h2>운영 현황</h2><p>API 프로세스와 PostgreSQL의 핵심 상태입니다.</p></div><div class="section-actions"><span id="overviewTime" class="timestamp">아직 갱신되지 않음</span><button class="button" id="refreshOverview">새로고침</button></div></div>
 <div class="cards">
  <article class="metric"><span class="metric-label">사용자</span><strong id="users">—</strong><small>삭제되지 않은 계정</small></article>
  <article class="metric"><span class="metric-label">활성 세션</span><strong id="sessions">—</strong><small>로그인 유지 중</small></article>
  <article class="metric"><span class="metric-label">독서 회차</span><strong id="runs">—</strong><small>전체 상태 합계</small></article>
  <article class="metric"><span class="metric-label">진척 기록</span><strong id="entries">—</strong><small>저장된 독서 기록</small></article>
  <article class="metric attention"><span class="metric-label">미처리 신고</span><strong id="openReports">—</strong><small>열림·검토 중</small></article>
  <article class="metric"><span class="metric-label">대기 이벤트</span><strong id="outbox">—</strong><small>Worker 처리 대기</small></article>
  <article class="metric"><span class="metric-label">알림 대기</span><strong id="pendingNotifications">—</strong><small>푸시 전달 대기</small></article>
  <article class="metric danger"><span class="metric-label">알림 실패</span><strong id="failedNotifications">—</strong><small>재확인 필요</small></article>
 </div>
 <div class="dashboard-grid"><article class="panel"><h3 class="panel-title">시스템 상태</h3>
  <div class="health-row"><div><div class="health-label">API 서버</div><div class="health-meta" id="uptime">가동 시간 —</div></div><span class="health-value" id="apiHealth">확인 전</span></div>
  <div class="health-row"><div><div class="health-label">PostgreSQL</div><div class="health-meta" id="dbSize">데이터베이스 크기 —</div></div><span class="health-value" id="dbHealth">확인 전</span></div>
  <div class="health-row"><div><div class="health-label">Go 런타임</div><div class="health-meta" id="runtimeMeta">버전 —</div></div><span class="health-value" id="memory">—</span></div>
 </article><aside class="panel"><h3 class="panel-title">운영 메모</h3><div class="guide"><strong>로그 보관 범위</strong>이 화면은 현재 API 프로세스의 최근 1,000건을 메모리에 보관합니다. 서버가 재시작되면 초기화됩니다.</div><div class="guide"><strong>장애 확인 순서</strong>오류 로그의 상태 코드와 경로를 본 뒤, Worker·PostgreSQL의 파일 로그를 함께 확인하세요.</div><span class="timestamp">관리자 키는 이 브라우저 탭의 sessionStorage에만 저장됩니다.</span></aside></div>
</section>

<section id="logs" class="view" role="tabpanel" hidden>
 <div class="section-head"><div><h2>실시간 API 로그</h2><p>인증 정보와 URL 쿼리는 수집하지 않습니다.</p></div><div id="streamState" class="stream-state"><span class="dot"></span><span>대기 중</span></div></div>
 <div class="log-tools"><select class="field" id="levelFilter" aria-label="로그 레벨"><option value="all">모든 레벨</option><option value="error">오류</option><option value="warn">경고</option><option value="info">정보</option></select><input class="field search" id="logSearch" type="search" placeholder="경로·메시지 검색" aria-label="로그 검색"><button class="button" id="pauseLogs">일시정지</button><button class="button" id="clearLogs">화면 비우기</button><label class="check"><input id="autoScroll" type="checkbox" checked> 자동 스크롤</label></div>
 <div class="log-shell"><div class="log-head"><span>시간</span><span>레벨</span><span>상태</span><span>요청 / 메시지</span></div><div id="logList" class="log-list" role="log" aria-live="polite"><div class="log-empty">관리자 키로 연결하면 최근 로그와 새 로그가 표시됩니다.</div></div></div>
</section>

<section id="moderation" class="view" role="tabpanel" hidden>
 <div class="section-head"><div><h2>신고 및 감사 기록</h2><p>조치 사유와 운영자 식별자가 감사 로그에 남습니다.</p></div><button class="button" id="refreshAudit">감사 기록 새로고침</button></div>
 <div class="moderation-grid"><div><div class="toolbar"><select class="field" id="reportStatus"><option value="open">미처리</option><option value="reviewing">검토 중</option><option value="resolved">조치 완료</option><option value="dismissed">기각</option><option value="all">전체</option></select><button class="button primary" id="loadReports">신고 불러오기</button></div><div id="reports" class="list"><div class="empty">연결 후 신고를 불러오세요.</div></div></div><aside><h3 class="panel-title">최근 감사 로그</h3><div id="audit" class="list"><div class="empty">감사 기록이 없습니다.</div></div></aside></div>
</section>
</main><script nonce="{{NONCE}}">
const $=id=>document.getElementById(id);
const state={key:sessionStorage.getItem('bookgyeol.adminKey')||'',connected:false,view:'dashboard',logs:[],logIds:new Set(),lastId:0,streamToken:0,controller:null,paused:false};
$('adminKey').value=state.key;
function headers(json=true){const value={'X-Admin-Key':state.key,'X-Admin-ID':$('adminId').value.trim()||'owner'};if(json)value['Content-Type']='application/json';return value}
function el(tag,value='',cls=''){const node=document.createElement(tag);if(cls)node.className=cls;node.textContent=value;return node}
function notify(value=''){const box=$('notice');box.textContent=value;box.classList.toggle('show',Boolean(value))}
function setConnection(online,label){state.connected=online;const box=$('connection');box.classList.toggle('online',online);box.querySelector('span:last-child').textContent=label||(online?'연결됨':'연결 안 됨')}
function setStream(live,label){const box=$('streamState');box.classList.toggle('live',live);box.querySelector('span:last-child').textContent=label}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||('요청 실패 ('+response.status+')'));return body}
function number(value){return new Intl.NumberFormat('ko-KR').format(value??0)}
function bytes(value){if(!Number.isFinite(value))return '—';const units=['B','KB','MB','GB'];let i=0;while(value>=1024&&i<units.length-1){value/=1024;i++}return value.toFixed(i?1:0)+' '+units[i]}
function duration(seconds){seconds=Math.max(0,seconds||0);const day=Math.floor(seconds/86400),hour=Math.floor(seconds%86400/3600),minute=Math.floor(seconds%3600/60);return [day&&day+'일',hour&&hour+'시간',minute&&minute+'분'].filter(Boolean).join(' ')||Math.floor(seconds)+'초'}
async function connect(){notify('');state.key=$('adminKey').value.trim();if(!state.key){notify('ADMIN_API_KEY를 입력해 주세요.');return}try{await refreshOverview();sessionStorage.setItem('bookgyeol.adminKey',state.key);setConnection(true,'보호된 API 연결됨');if(state.view==='logs')startLogStream()}catch(error){setConnection(false,'인증 실패');notify(error.message)}}
function disconnect(){stopLogStream();state.key='';state.connected=false;sessionStorage.removeItem('bookgyeol.adminKey');$('adminKey').value='';setConnection(false);setStream(false,'대기 중');notify('관리자 연결을 해제했습니다.')}
async function refreshOverview(){if(!state.key)throw new Error('관리자 키를 입력해 주세요.');const body=await api('/v1/admin/overview');const s=body.storage;[['users',s.users],['sessions',s.activeSessions],['runs',s.readingRuns],['entries',s.progressEntries],['openReports',s.openReports],['outbox',s.pendingOutbox],['pendingNotifications',s.pendingNotifications],['failedNotifications',s.failedNotifications]].forEach(([id,value])=>$(id).textContent=number(value));$('reportBadge').textContent=number(s.openReports);$('reportBadge').hidden=!s.openReports;$('apiHealth').textContent=body.status==='ok'?'정상':'확인 필요';$('dbHealth').textContent=body.database==='connected'?'연결됨':'연결 오류';$('uptime').textContent='가동 시간 '+duration(body.uptimeSeconds);$('dbSize').textContent='데이터베이스 크기 '+bytes(s.databaseSizeBytes);$('runtimeMeta').textContent=body.goVersion+' · 고루틴 '+number(body.goroutines);$('memory').textContent=bytes(body.memoryBytes);$('overviewTime').textContent='마지막 갱신 '+new Date(body.generatedAt).toLocaleTimeString();setConnection(true,'보호된 API 연결됨');return body}
function switchView(name){state.view=name;document.querySelectorAll('.tab').forEach(tab=>{const active=tab.dataset.view===name;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active))});document.querySelectorAll('.view').forEach(view=>view.hidden=view.id!==name);if(name==='logs'&&state.connected)startLogStream();else stopLogStream();if(name==='moderation'&&state.connected)Promise.all([loadReports(),loadAudit()]).catch(error=>notify(error.message));if(name==='dashboard'&&state.connected)refreshOverview().catch(error=>notify(error.message))}
function addLog(entry){if(!entry||state.logIds.has(entry.id))return;state.logIds.add(entry.id);state.logs.push(entry);state.lastId=Math.max(state.lastId,entry.id||0);while(state.logs.length>500){const removed=state.logs.shift();state.logIds.delete(removed.id)}if(!state.paused)renderLogs()}
function renderLogs(){const box=$('logList'),level=$('levelFilter').value,query=$('logSearch').value.trim().toLowerCase();const items=state.logs.filter(item=>(level==='all'||item.level===level)&&(!query||[item.message,item.method,item.path,item.detail,item.status].join(' ').toLowerCase().includes(query))).slice(-250);if(!items.length){box.replaceChildren(el('div',state.paused?'로그 표시가 일시정지되었습니다.':'조건에 맞는 로그가 없습니다.','log-empty'));return}const fragment=document.createDocumentFragment();items.forEach(item=>{const row=el('div','','log-row'),time=el('span',new Date(item.occurredAt).toLocaleTimeString('ko-KR',{hour12:false}),'log-time'),levelNode=el('span',item.level.toUpperCase(),'log-level '+item.level),status=el('span',item.status?String(item.status):'—','log-status'),main=el('div','','log-main'),message=el('div',item.message,'log-message');const context=[item.method,item.path,item.durationMs>=0&&item.durationMs+'ms',item.responseBytes?bytes(item.responseBytes):'',item.detail].filter(value=>value!==false&&value!=='').join(' · ');main.append(message,el('div',context,'log-context'));row.append(time,levelNode,status,main);fragment.append(row)});box.replaceChildren(fragment);if($('autoScroll').checked)box.scrollTop=box.scrollHeight}
function stopLogStream(){state.streamToken++;if(state.controller)state.controller.abort();state.controller=null;if(state.view==='logs')setStream(false,state.paused?'일시정지':'연결 대기')}
async function startLogStream(){if(!state.connected||!state.key||state.paused)return;stopLogStream();const token=state.streamToken;setStream(true,'실시간 수신 중');while(token===state.streamToken&&state.connected&&state.view==='logs'&&!state.paused){const controller=new AbortController();state.controller=controller;try{const response=await fetch('/v1/admin/logs/stream?after='+encodeURIComponent(state.lastId),{headers:headers(false),signal:controller.signal});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error?.message||'로그 스트림 연결 실패')}const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';while(true){const result=await reader.read();if(result.done)break;pending+=decoder.decode(result.value,{stream:true});const lines=pending.split('\n');pending=lines.pop();for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='log')addLog(event.entry)}}}catch(error){if(error.name!=='AbortError'){setStream(false,'재연결 중');notify(error.message)}}if(token===state.streamToken)await new Promise(resolve=>setTimeout(resolve,700))}if(token===state.streamToken)setStream(false,'연결 대기')}
function reportCard(item){const card=el('article','','report'),meta=el('div','','meta');[item.status,item.reason,item.targetType,item.targetId,item.reporterNickname||item.reporterId,new Date(item.createdAt).toLocaleString()].forEach(value=>meta.append(el('span',value,'pill')));card.append(meta,el('p',item.detail||'상세 내용 없음','detail'));const actions=el('div','','actions');[['dismiss','기각'],['hide','숨김'],['warn','경고'],['suspend','7일 정지'],['ban','차단']].forEach(([action,label])=>{const button=el('button',label,'button '+(action==='ban'?'danger':''));button.onclick=()=>resolveReport(item.id,action);actions.append(button)});card.append(actions);return card}
async function loadReports(){const box=$('reports');box.replaceChildren(el('div','불러오는 중…','empty'));const body=await api('/v1/admin/reports?status='+encodeURIComponent($('reportStatus').value));box.replaceChildren(...(body.items.length?body.items.map(reportCard):[el('div','해당 신고가 없습니다.','empty')]));return body}
async function resolveReport(id,action){const reason=prompt('조치 사유를 입력하세요.');if(!reason)return;if((action==='ban'||action==='hide')&&!confirm('이 조치를 실행할까요? 감사 기록에 남습니다.'))return;try{await api('/v1/admin/reports/'+id,{method:'PATCH',body:JSON.stringify({action,reason,durationHours:action==='suspend'?168:0})});await Promise.all([loadReports(),loadAudit(),refreshOverview()])}catch(error){notify(error.message)}}
async function loadAudit(){const box=$('audit'),body=await api('/v1/admin/moderation/actions?limit=30');box.replaceChildren(...(body.items.length?body.items.map(item=>{const card=el('article','','audit-item');card.append(el('strong',item.action+' · '+item.targetType),el('div',item.reason,'reason'),el('div',item.operatorId+' · '+new Date(item.createdAt).toLocaleString(),'meta'));return card}):[el('div','감사 기록이 없습니다.','empty')]));return body}
function applyTheme(value){document.documentElement.dataset.theme=value==='auto'?'':value;localStorage.setItem('bookgyeol.adminTheme',value);$('themeBtn').title='테마: '+({auto:'시스템',light:'라이트',dark:'다크'}[value]);$('themeBtn').dataset.value=value}
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>switchView(tab.dataset.view));
$('connectBtn').onclick=connect;$('disconnectBtn').onclick=disconnect;$('refreshOverview').onclick=()=>refreshOverview().catch(error=>notify(error.message));$('loadReports').onclick=()=>loadReports().catch(error=>notify(error.message));$('refreshAudit').onclick=()=>loadAudit().catch(error=>notify(error.message));$('reportStatus').onchange=()=>loadReports().catch(error=>notify(error.message));
$('pauseLogs').onclick=()=>{state.paused=!state.paused;$('pauseLogs').textContent=state.paused?'다시 시작':'일시정지';if(state.paused)stopLogStream();else{renderLogs();startLogStream()}};$('clearLogs').onclick=()=>{state.logs=[];state.logIds.clear();renderLogs()};$('levelFilter').onchange=renderLogs;$('logSearch').oninput=renderLogs;
$('themeBtn').onclick=()=>{const order=['auto','light','dark'],current=$('themeBtn').dataset.value||'auto';applyTheme(order[(order.indexOf(current)+1)%order.length])};applyTheme(localStorage.getItem('bookgyeol.adminTheme')||'auto');
setInterval(()=>{if(state.connected&&state.view==='dashboard')refreshOverview().catch(error=>notify(error.message))},15000);
if(state.key)connect();
</script></body></html>`
